spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/webservice
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show_sql: true
        format_sql: true
#        default_batch_fetch_size: 100

logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace